version: 0.2

phases:
  install:
    commands:
      - curl -sL https://deb.nodesource.com/setup_15.x | bash -
      - apt install -y nodejs
      - npm install npm@latest -g
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
      
